name: Therese lernt noch github
on:
 push
 # pull_request:
   # types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
    - run: ls -la
    - run: echo "hallo erde"
    - run: docker run hello-world 
